
#This category holds general values that will mostly be customized by most.
["Starting Configurations"]
	#This value modifies how many hearts you'll start at in a world. 2 would mean 1 extra heart, -2 would mean 1 less heart. If you have lives enabled, you'll gain a life when you get max hearts double your starting hearts. EX: If 3 hearts is your starting value, you'll gain a life if you get 3 more hearts. 
	#Range: > -19
	"Starting HitPoint Difference:" = 0
	#When this is true, you will lose hearts when killed by a player. Otherwise, you can lose max hearts just by any sorts of death.. (This is overridden by the mob value below if it's true)
	"Lose Hearts Only When Killed By a Player:" = false
	#When this is true, you will lose hearts when killed by a mob. Otherwise, you can lose max hearts just by any sorts of death.
	"Lose Hearts Only When Killed By an Entity:" = false
	#This values modifies the amount of hit points that should be lost when you die. The same also applies when you gain max health from lifestealing. 2 hit points = 1 health.
	#Range: > 1
	"Amount of HitPoints/Health Lost/Given Upon Death/Kill:" = 2
	#This value determines if a PLAYER should lose HEARTS AT ALL.
	"Disable Heart Loss:" = false
	#When a player is revived with the Revive Crystal, this value determines whether or not a chat message will be sent indicating they have been brought back from the dead.
	"Silently Revive Players:" = false
	#In multiplayer, this value determines whether heads spawn or not when a player dies. NOTE: In singleplayer, this value is always false.
	"Players Spawn Their Head Upon Death:" = true

#This category is the configuration for items and enchantments in this mod
["Items and Enchantments"]
	#This is the amount of hit points a Heart Crystal should give when used. 2 HitPoints = 1 Heart, 3 = 1.5 Heart.
	#Range: > 1
	"Amount of HitPoints Heart Crystal Permanently Gives:" = 2
	#The percentage of max health a heart core should heal when used.
	#Range: 0.01 ~ 1.0
	"Percentage of max Health Heart Core Heals" = 0.25
	#If a max is set for the amount of hearts you can get, this option when true, makes it so players can't eat heart crystals if they're already at the max.
	"Prevent Players From Using Heart Crystals If At Max Hearts:" = true
	#If this option is true, a player cannot eat heart cores if they are already at their max health.
	"Prevent Players From Using Heart Cores If At Max Health:" = true
	#If you just want the generic Lifesteal mod, you can disable this and nobody can gain hearts through Heart Crystals but only through lifestealing.
	"Disable Heart Crystals:" = false
	#Heart Cores can heal on default 25% of your health if right clicked. This value determines if they should be disabled.
	"Disable Heart Cores:" = false
	#This value determines whether or not revive crystals are disabled. If you're in singleplayer, this value is always true.
	"Disable Revive Crystals:" = false

#This category is everything related to life stealing from someone.
["Lifesteal Related"]
	#This option changes the entire mod into more of a permanent heart gaining system. This makes it so nobody can gain hearts from lifestealing but ONLY through Heart Crystals. MOBS can still take your hearts away if they kill you though, UNLESS you have that option disabled.
	"Disable Lifesteal:" = true
	#This value determines if a player should still earn hearts from a player they killed even if the player doesn't have hearts to spare. EX: MinimumHeartHave
	"Players Gain Hearts From No Heart Players:" = false

#This category will hold the maximums for certain values
[Maximums]
	#This value makes a limit SET after your Starting HitPoint Difference for how many hit points/hearts a player can get. 2 hit points = 1 heart. Set this to less than 1 to disable the feature.
	#Range: > -1
	"Maximum Amount of Health/Hitpoints a Player can get:" = 6
	#This value makes a limit set on how many hit points/hearts a player can lose, this value is actually set depending on the Starting Health Difference. EX: Starting Health Difference - MinimumHeartHave. Set this to less than 0 to disable the feature.
	#Range: > -1
	"Maximum Amount Of Health/Hitpoints a Player can Lose:" = -1
	#When a player has reached max hearts or attempt to go higher than the max, if this value is true, a message will let them know indicating they cannot go higher.
	"Tell Players if They Have Reached max Hearts:" = true

#This category holds values related to commands.
[Commands]
	#This just makes it so when an admin changed a person's hitpoints, this value would determine if the game should tell the person in chat that their hitpoints was changed.
	"Tell Players if Their HitPoint Difference Changed:" = true

	[Commands.Withdrawing]
		#This value determines the advancement used to unlock withdrawing. You would find the advancement you want to use by using the ID of the advancement which is found with the /advancement command. If the value is empty, withdraw will be unlocked automatically.
		"The Advancement Needed to Unlock Withdrawing:" = "lifesteal:lifesteal/get_heart_crystal"
		#This value determines what text will pop up when a player hasn't unlocked withdrawing. If this value is empty, no text will pop up.
		"The Text Shown When Withdrawing Isn't Unlocked:" = "You need to at least have gotten one heart crystal in this world to withdraw"

#This category holds values that don't fit in other categories OR are not made for gameplay usage.
["Misc/Fun"]
	#When this is false, you can only gain hearts from killing players. Otherwise, any mob will give you hearts.
	"Killing any Mobs Gives Hearts:" = false

